version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "story-analysis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ferxbfg4v7nd"
s3_prefix = "story-analysis"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
