AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  story-survey-api

  Sample SAM Template for story-survey-api

Parameters:
  TABLE_NAME:
    Type: String
    Default: 'localStoryReview'
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'

  ENVIRONMENT_NAME:
    Description: 'Environment name'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'Production'
  
  DYNAMODB_ENDPOINT:
    Description: 'DynamoDb endpoint'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'http://host.docker.internal:8000'

# More info about Globals: 
Globals:
  Function:
    # Properties of AWS::Serverless::Function
    Timeout: 1000
    Environment:
      Variables:
        API_NAME: story_survey_api
        ENVIRONMENT_NAME: !Ref ENVIRONMENT_NAME
        DYNAMODB_ENDPOINT: !Ref DYNAMODB_ENDPOINT
  Api:
    # Properties of AWS::Serverless::Api
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TABLE_NAME
      AttributeDefinitions:
        - AttributeName: story_link
          AttributeType: S
        - AttributeName: user_code
          AttributeType: S
      KeySchema:
        - AttributeName: story_link
          KeyType: "HASH"
        - AttributeName: user_code
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # P36NumpyPandaLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #       LayerName: P36NumpyPandaLayer
  #       Description: P36NumpyPanda (Python 3.6, numpy, panda, regex)
  #       ContentUri: layers/P36NumpyPanda
  #       CompatibleRuntimes:
  #         - python3.6

  # NltkLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #       LayerName: NltkLayer
  #       Description: Nltk toolkit Layer (nltk)
  #       ContentUri: layers/NltkBasic
  #       CompatibleRuntimes:
  #         - python3.6

  # NltkLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: NltkLayerNltkLayer
  #     Description: NltkLayer
  #     ContentUri: arn:aws:lambda:eu-west-1:540686626730:layer:StoryLayer:3
  #     CompatibleRuntimes:
  #       - python3.8


  SurveyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: survey/
      Handler: app.save_handler
      Runtime: python3.8
      Layers:
        - arn:aws:lambda:eu-west-1:540686626730:layer:StoryLayer:6
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TABLE_NAME
      Environment:
        Variables:
          TABLE_NAME: !Ref TABLE_NAME
      Events:
        survey:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /survey
            Method: post
            

  LcFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lc/
      Handler: app.lambda_lc_handler
      Layers:
        - arn:aws:lambda:eu-west-1:540686626730:layer:StoryLayer:6
      Runtime: python3.8
      Events:
        lc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lc
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LcApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lc/"
  LcFunction:
    Description: "Lc Lambda Function ARN"
    Value: !GetAtt LcFunction.Arn
  LcIamRole:
    Description: "Implicit IAM Role created for Lc function"
    Value: !GetAtt LcFunctionRole.IamRoleArn

  SurveyApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lc/"
  SurveyFunction:
    Description: "Survey Lambda Function ARN"
    Value: !GetAtt SurveyFunction.Arn
  SurveyIamRole:
    Description: "Implicit IAM Role created for Survey function"
    Value: !GetAtt SurveyFunctionRole.IamRoleArn
