AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  story-survey-api

  Sample SAM Template for story-survey-api

Parameters:

  ENVIRONMENT_NAME:
    Description: 'Environment name'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'Production'
  
  DYNAMODB_ENDPOINT:
    Description: 'DynamoDb endpoint'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'http://host.docker.internal:8000'

# More info about Globals: 
Globals:
  Function:
    # Properties of AWS::Serverless::Function
    Timeout: 1000
    Environment:
      Variables:
        API_NAME: story_survey_api
        ENVIRONMENT_NAME: !Ref ENVIRONMENT_NAME
        DYNAMODB_ENDPOINT: !Ref DYNAMODB_ENDPOINT
  Api:
    # Properties of AWS::Serverless::Api
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    
Resources:

  P36NumpyPandaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: P36NumpyPandaLayer
        Description: P36NumpyPanda (Python 3.6, numpy, panda)
        ContentUri: layers/P36NumpyPanda
        CompatibleRuntimes:
          - python3.6

  NltkLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: NltkLayer
        Description: Nltk toolkit Layer (nltk)
        ContentUri: layers/NltkBasic
        CompatibleRuntimes:
          - python3.6

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  SurveyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: survey/
      Handler: app.save_handler
      Runtime: python3.6
      Environment:
        Variables:
          TABLE_NAME: story_survey
      Events:
        survey:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /survey
            Method: post

  LcFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lc/
      Handler: app.lambda_lc_handler
      Layers:
        - !Ref P36NumpyPandaLayer
        - !Ref NltkLayer
      Runtime: python3.6
      Events:
        lc:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lc
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  LcApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lc/"
  LcFunction:
    Description: "Lc Lambda Function ARN"
    Value: !GetAtt LcFunction.Arn
  LcIamRole:
    Description: "Implicit IAM Role created for Lc function"
    Value: !GetAtt LcFunctionRole.IamRoleArn

  SurveyApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lc/"
    SurveyFunction:
    Description: "Survey Lambda Function ARN"
    Value: !GetAtt SurveyFunction.Arn
    SurveyIamRole:
    Description: "Implicit IAM Role created for Survey function"
    Value: !GetAtt SurveyFunctionRole.IamRoleArn
